export const SET_USER = 'SET_USER'
export const DELETE_USER = 'DELETE_USER'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SET_THEME = 'SET_THEME'
export const SET_CONNECTED = 'SET_CONNECTED'
export const SET_CHAT_TIMELINE = 'SET_CHAT_TIMELINE'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const ADDED_TO_GROUP = 'ADDED_TO_GROUP'